import { createStyles } from '../../../../../shared/styles/theme';

export const nodePaletteStyles = createStyles((theme) => ({
  paletteContainer: {
    marginBottom: theme.spacing.md,
  },
  nodeTypesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing.xl,
    padding: theme.spacing.md,
  },
  nodeInnerContainer: {
    background: 'none',
    border: 'none',
    padding: 0,
    margin: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paletteNode: {
    position: 'relative',
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: theme.colors.nodeBg,
    border: `1px solid ${theme.colors.border}`,
    marginBottom: theme.spacing.xs,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'grab',
    color: theme.colors.textMuted,
    fontSize: theme.fontSize.md,
    textAlign: 'center',
    width: '100%',
    transition: theme.transitions.default,
  },
  paletteNodeHover: {
    backgroundColor: theme.colors.nodeHoverBg,
    borderColor: theme.colors.primary,
  },
  paletteNodeTypesContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing.md,
  },
  connectionHandleRight: {
    position: 'absolute',
    width: theme.spacing.md,
    height: theme.spacing.md,
    borderRadius: theme.borderRadius.round,
    backgroundColor: theme.colors.white,
    border: `1px solid ${theme.colors.border}`,
    right: `-${theme.spacing.md}`,
    top: '50%',
    transform: 'translateY(-50%)',
  },
  connectionHandleLeft: {
    position: 'absolute',
    width: theme.spacing.md,
    height: theme.spacing.md,
    borderRadius: theme.borderRadius.round,
    backgroundColor: theme.colors.white,
    border: `1px solid ${theme.colors.border}`,
    left: `-${theme.spacing.md}`,
    top: '50%',
    transform: 'translateY(-50%)',
  },
}));
